test_rootfs_name = 'ugrd-test-rootfs'
test_rootfs_build_dir = 'initramfs_test_rootfs'
test_image_size = 16

test_copy_config = ["_mounts", "mounts", "out_dir", "tmpdir", "clean", "test_image_size", "test_no_rootfs", "test_flag", "cryptsetup"]
kmod_init = ["ata_piix", "sd_mod"]

test_memory = '256M'
test_cpu = 'host'
test_arch = 'x86_64'
test_timeout = 15
test_cmdline = 'console=ttyS0,115200 panic=1'
#qemu_bool_args = ['nographic', 'no-reboot', 'enable-kvm']
qemu_bool_args = ['nographic', 'enable-kvm' ]

[imports.build_pre]
"ugrd.base.test" = [ "init_test_vars" ]

[imports.tests]
"ugrd.base.test" = [ "test_image" ]

[custom_parameters]
test_kernel = "Path"  # Define the kernel to use for the test
test_memory = "str"  # Define the amount of memory to use for the test image (passed to qemu)
test_cpu = "str"  # Define the CPU to use for the test image (passed to qemu)
test_arch = "str"  # Define the qemu arch (added to the qemu-system- command)
test_cmdline = "str"  # Define the kernel command line for the test image
test_timeout = "int"  # Define the timeout for the test
test_image_size = "int"  # Define the size of the test image, in MB
test_flag = "str"  # Define the success flag for the test
test_no_rootfs = "bool"  # Toggle to run tests without mounting the root image
test_rootfs_name = "str"  # Define the name of the rootfs image
test_rootfs_build_dir = "Path"  # Define the build directory for the rootfs image
qemu_bool_args = "NoDupFlatList"  # Define the qemu boolean arguments
