binaries = ["/lib/systemd/systemd-udevd"]
dependencies = ["/etc/group"]


[imports.build_tasks]
"ugrd.base.udev" = [ "pull_udev_deps" ]

[imports.init_pre]
"ugrd.base.udev" = [ "start_udev" ]

[import_order.before]
"start_udev" = [ "load_modules" ]

[import_order.after]
"start_udev" = ["mount_base"]
>>>>>>> a1b17bc (fix)
