modules = [ "ugrd.fs.livecd", "ugrd.kmod.usb" ]
kmod_init = ["hfsplus"]  # Needed for the Gentoo LiveCD
livecd_label = "gentoo-amd64-livegui"
livecd_persistence = true
livecd_persistence_label = "Appended3"
