cmdline_strings = [ "resume" ]

[imports.init_main] 
"ugrd.fs.resume" = [ "handle_resume" ]

[import_order.before]
handle_resume = "mount_fstab"

[custom_parameters]
swap_uuid = "str"  # The UUID of the swap partition, used to resume from hibernation.
